import type { Candle } from './indicators.service.js'

export type BacktestCandle = Candle & { date?: string; timestamp?: string | number }
export type BacktestStrategy = 'confluence_based' | 'elliott_wave' | 'wyckoff' | 'breakout' | 'trend_following'
export type BacktestOptions = { commission?: number; slippage?: number; initialCapital?: number; maxVolumeParticipation?: number; stopLossPct?: number; targetPct?: number; maxHoldingBars?: number; from?: string; to?: string }
type Direction = 'long' | 'short'
type Signal = { direction: Direction; reason: string; score?: number }
type Trade = { entry_date: string; exit_date: string; entry_index: number; exit_index: number; direction: Direction; entry_price: number; exit_price: number; gross_return_pct: number; net_return_pct: number; pnl: number; holding_days: number; exit_reason: 'stop' | 'target' | 'reversal' | 'time'; volume_limit_respected: boolean; reason: string }

const STRATEGIES: BacktestStrategy[] = ['confluence_based', 'elliott_wave', 'wyckoff', 'breakout', 'trend_following']
const clamp = (value: number, min = 0, max = 100) => Math.max(min, Math.min(max, value))
const round = (value: number, digits = 2) => Number.isFinite(value) ? Number(value.toFixed(digits)) : 0
const finite = (value: unknown, fallback = 0) => typeof value === 'number' && Number.isFinite(value) ? value : fallback
const close = (candle: BacktestCandle) => finite(candle.close)
const open = (candle: BacktestCandle) => finite(candle.open, close(candle))
const high = (candle: BacktestCandle) => finite(candle.high, Math.max(open(candle), close(candle)))
const low = (candle: BacktestCandle) => finite(candle.low, Math.min(open(candle), close(candle)))
const volume = (candle: BacktestCandle) => Math.max(0, finite(candle.volume))
const dateOf = (candle: BacktestCandle, index: number) => candle.date ?? (candle.timestamp == null ? String(index) : new Date(candle.timestamp).toISOString().slice(0, 10))
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0
const highest = (candles: BacktestCandle[], from: number, to: number) => Math.max(...candles.slice(from, to).map(high))
const lowest = (candles: BacktestCandle[], from: number, to: number) => Math.min(...candles.slice(from, to).map(low))

function emaAt(candles: BacktestCandle[], index: number, period: number) { const alpha = 2 / (period + 1); let value = close(candles[0]); for (let i = 1; i <= index; i++) value = close(candles[i]) * alpha + value * (1 - alpha); return value }
function rsiAt(candles: BacktestCandle[], index: number, period = 14) { if (index < period) return null; let gains = 0, losses = 0; for (let i = index - period + 1; i <= index; i++) { const change = close(candles[i]) - close(candles[i - 1]); gains += Math.max(change, 0); losses += Math.max(-change, 0) } if (losses === 0) return 100; return 100 - 100 / (1 + gains / losses) }
function dateRange(candles: BacktestCandle[]) { return { from: candles.length ? dateOf(candles[0], 0) : null, to: candles.length ? dateOf(candles.at(-1)!, candles.length - 1) : null } }
function signalFor(strategy: BacktestStrategy, candles: BacktestCandle[], index: number): Signal | null {
	if (index < 21) return null
	const price = close(candles[index]), previous = close(candles[index - 1]), avgVolume = average(candles.slice(index - 20, index).map(volume)), rsi = rsiAt(candles, index), ema20 = emaAt(candles, index, 20), ema50 = emaAt(candles, index, Math.min(50, index + 1)), trend = price > ema20 && ema20 > emaAt(candles, Math.max(0, index - 1), 20), previousTrend = previous > emaAt(candles, Math.max(0, index - 1), 20), rangeHigh = highest(candles, index - 20, index), rangeLow = lowest(candles, index - 20, index), currentVolume = volume(candles[index])
	if (strategy === 'confluence_based') { const score = (price > ema20 ? 25 : 0) + (ema20 > ema50 ? 20 : 0) + (rsi != null && rsi > 52 && rsi < 72 ? 25 : rsi != null && rsi < 35 ? 20 : 0) + (currentVolume > avgVolume * 1.1 ? 20 : 0) + (price > previous ? 10 : 0); if (score > 70) return { direction: 'long', reason: 'confluence_score_above_70', score }; if (score < 40) return { direction: 'short', reason: 'confluence_score_below_40', score }; return null }
	if (strategy === 'elliott_wave') { const momentum = price / close(candles[index - 5]) - 1; if (momentum > 0.035 && price > ema20) return { direction: 'long', reason: 'impulsive_wave_momentum' }; if (momentum < -0.035 && price < ema20) return { direction: 'short', reason: 'wave_five_reversal_risk' }; return null }
	if (strategy === 'wyckoff') { const spring = low(candles[index]) < rangeLow && price > rangeLow && currentVolume > avgVolume; const sos = price > rangeHigh && currentVolume > avgVolume * 1.2; const upthrust = high(candles[index]) > rangeHigh && price < rangeHigh && currentVolume > avgVolume; if (spring || sos) return { direction: 'long', reason: spring ? 'spring_confirmed' : 'sign_of_strength' }; if (upthrust) return { direction: 'short', reason: 'upthrust_confirmed' }; return null }
	if (strategy === 'breakout') { if (price > rangeHigh && currentVolume > avgVolume * 1.2) return { direction: 'long', reason: 'resistance_breakout_with_volume' }; if (price < rangeLow && currentVolume > avgVolume * 1.2) return { direction: 'short', reason: 'support_breakdown_with_volume' }; return null }
	if (strategy === 'trend_following') { if (price > ema50 && !previousTrend && trend) return { direction: 'long', reason: 'ema50_bullish_cross' }; if (price < ema50 && previousTrend && !trend) return { direction: 'short', reason: 'ema50_bearish_cross' }; return null }
	return null
}

function executeTrades(candles: BacktestCandle[], strategy: BacktestStrategy, options: Required<Pick<BacktestOptions, 'commission' | 'slippage' | 'initialCapital' | 'maxVolumeParticipation' | 'stopLossPct' | 'targetPct' | 'maxHoldingBars'>>): { trades: Trade[]; equity_curve: Array<{ date: string; equity: number }>; rejected_signals: number } {
	const trades: Trade[] = [], equity: Array<{ date: string; equity: number }> = [{ date: dateOf(candles[0], 0), equity: options.initialCapital }]; let capital = options.initialCapital, index = 21, rejectedSignals = 0
	while (index < candles.length - 1) {
		const signal = signalFor(strategy, candles, index)
		if (!signal) { equity.push({ date: dateOf(candles[index], index), equity: capital }); index++; continue }
		const execution = candles[index + 1], rawEntry = open(execution), entry = signal.direction === 'long' ? rawEntry * (1 + options.slippage) : rawEntry * (1 - options.slippage), availableVolume = volume(execution), participationLimit = availableVolume * options.maxVolumeParticipation
		if (!Number.isFinite(entry) || entry <= 0 || participationLimit <= 0) { rejectedSignals++; index++; continue }
		const requestedUnits = capital / entry
		if (requestedUnits > participationLimit) { rejectedSignals++; index++; continue }
		const stop = signal.direction === 'long' ? entry * (1 - options.stopLossPct) : entry * (1 + options.stopLossPct), target = signal.direction === 'long' ? entry * (1 + options.targetPct) : entry * (1 - options.targetPct); let exitIndex = Math.min(candles.length - 1, index + 1 + options.maxHoldingBars), exitReason: Trade['exit_reason'] = 'time'
		for (let future = index + 2; future <= exitIndex; future++) { const hitStop = signal.direction === 'long' ? low(candles[future]) <= stop : high(candles[future]) >= stop; const hitTarget = signal.direction === 'long' ? high(candles[future]) >= target : low(candles[future]) <= target; if (hitStop) { exitIndex = future; exitReason = 'stop'; break } if (hitTarget) { exitIndex = future; exitReason = 'target'; break } const reversal = signal.direction === 'long' ? close(candles[future]) < emaAt(candles, future, 20) : close(candles[future]) > emaAt(candles, future, 20); if (reversal) { exitIndex = future; exitReason = 'reversal'; break } }
		const rawExit = close(candles[exitIndex]), exit = signal.direction === 'long' ? rawExit * (1 - options.slippage) : rawExit * (1 + options.slippage), grossReturn = signal.direction === 'long' ? exit / entry - 1 : entry / exit - 1, netReturn = grossReturn - options.commission * 2, pnl = capital * netReturn, holdingDays = Math.max(1, exitIndex - (index + 1)); capital += pnl; trades.push({ entry_date: dateOf(execution, index + 1), exit_date: dateOf(candles[exitIndex], exitIndex), entry_index: index + 1, exit_index: exitIndex, direction: signal.direction, entry_price: round(entry), exit_price: round(exit), gross_return_pct: round(grossReturn * 100), net_return_pct: round(netReturn * 100), pnl: round(pnl), holding_days: holdingDays, exit_reason: exitReason, volume_limit_respected: true, reason: signal.reason }); equity.push({ date: dateOf(candles[exitIndex], exitIndex), equity: round(capital) }); index = Math.max(exitIndex + 1, index + 1)
	}
	return { trades, equity_curve: equity, rejected_signals: rejectedSignals }
}

function returnsFromTrades(trades: Trade[]) { return trades.map(trade => trade.net_return_pct / 100) }
function maxDrawdown(equity: Array<{ equity: number }>) { let peak = equity[0]?.equity ?? 0, worst = 0, averageDd = 0, count = 0; for (const point of equity) { peak = Math.max(peak, point.equity); const drawdown = peak ? (point.equity / peak - 1) * 100 : 0; worst = Math.min(worst, drawdown); if (drawdown < 0) { averageDd += drawdown; count++ } } return { max: round(worst), average: round(count ? averageDd / count : 0) } }
function metrics(trades: Trade[], equity: Array<{ date: string; equity: number }>, initialCapital: number) { const returns = returnsFromTrades(trades), wins = trades.filter(trade => trade.net_return_pct > 0), losses = trades.filter(trade => trade.net_return_pct < 0), grossProfit = wins.reduce((sum, trade) => sum + trade.pnl, 0), grossLoss = Math.abs(losses.reduce((sum, trade) => sum + trade.pnl, 0)), mean = returns.length ? average(returns) : 0, volatility = returns.length > 1 ? Math.sqrt(average(returns.map(value => (value - mean) ** 2))) : 0, downside = returns.length ? Math.sqrt(average(returns.filter(value => value < 0).map(value => value ** 2))) : 0, periodYears = Math.max(1 / 252, (trades.at(-1)?.exit_index ?? 252) / 252), totalReturn = equity.length ? equity.at(-1)!.equity / initialCapital - 1 : 0, annualizedReturn = Math.pow(1 + totalReturn, 1 / periodYears) - 1, dd = maxDrawdown(equity), avgGain = wins.length ? average(wins.map(trade => trade.net_return_pct)) : 0, avgLoss = losses.length ? average(losses.map(trade => trade.net_return_pct)) : 0, winRate = trades.length ? wins.length / trades.length * 100 : 0, consecutive = (positive: boolean) => { let best = 0, current = 0; for (const trade of trades) { if ((trade.net_return_pct > 0) === positive) { current++; best = Math.max(best, current) } else current = 0 } return best }, expectancy = (winRate / 100 * avgGain) + ((1 - winRate / 100) * avgLoss), profitFactor = grossLoss ? grossProfit / grossLoss : grossProfit > 0 ? Infinity : 0, maxDdAbs = Math.abs(dd.max)
	return { total_trades: trades.length, performance: { win_rate: round(winRate), avg_gain_pct: round(avgGain), avg_loss_pct: round(avgLoss), profit_factor: Number.isFinite(profitFactor) ? round(profitFactor) : null, expectancy: round(expectancy), total_return_pct: round(totalReturn * 100) }, risk_metrics: { max_drawdown_pct: dd.max, avg_drawdown_pct: dd.average }, risk_adjusted: { sharpe_ratio: round(volatility ? ((annualizedReturn - 0.04) / (volatility * Math.sqrt(252))) : 0), sortino_ratio: round(downside ? ((annualizedReturn - 0.04) / (downside * Math.sqrt(252))) : 0), calmar_ratio: round(maxDdAbs ? annualizedReturn / (maxDdAbs / 100) : 0) }, trade_statistics: { avg_holding_days: round(trades.length ? average(trades.map(trade => trade.holding_days)) : 0), max_consecutive_wins: consecutive(true), max_consecutive_losses: consecutive(false) } }
}
function separationStats(candles: BacktestCandle[], strategy: BacktestStrategy, options: any) { const split = Math.floor(candles.length * 0.7), inSample = candles.slice(0, split), outOfSample = candles.slice(Math.max(0, split - 21)), inTrades = executeTrades(inSample, strategy, options), outTrades = executeTrades(outOfSample, strategy, options); return { in_sample: { ...metrics(inTrades.trades, inTrades.equity_curve, options.initialCapital), period: dateRange(inSample) }, out_of_sample: { ...metrics(outTrades.trades, outTrades.equity_curve, options.initialCapital), period: dateRange(outOfSample) } } }
function walkForward(candles: BacktestCandle[], strategy: BacktestStrategy, options: any) { const windows = []; const size = Math.floor(candles.length / 5); for (let index = 0; index < 5; index++) { const window = candles.slice(index * size, index === 4 ? candles.length : (index + 1) * size); const trainEnd = Math.max(22, Math.floor(window.length * 0.7)); const test = window.slice(Math.max(0, trainEnd - 21)); const executed = executeTrades(test, strategy, options); windows.push({ window: index + 1, train_period: dateRange(window.slice(0, trainEnd)), test_period: dateRange(test), train_bars: trainEnd, test_bars: test.length, ...metrics(executed.trades, executed.equity_curve, options.initialCapital), equity_curve: executed.equity_curve }) } return windows }
function robustness(separation: ReturnType<typeof separationStats>, walk: ReturnType<typeof walkForward>, totalTrades: number, maxDrawdownPct: number, sharpe: number) { const consistency = Math.max(0, 1 - Math.abs(separation.in_sample.performance.win_rate - separation.out_of_sample.performance.win_rate) / 100) * 25; const wfReturns = walk.map(window => window.performance.total_return_pct), averageReturn = average(wfReturns), consistencyWf = averageReturn === 0 ? 0 : Math.max(0, 1 - (Math.max(...wfReturns) - Math.min(...wfReturns)) / Math.max(Math.abs(averageReturn), 1)) * 25; const tradeScore = Math.min(20, totalTrades / 100 * 20), ddScore = Math.max(0, 15 * (1 - Math.abs(maxDrawdownPct) / 30)), sharpeScore = Math.min(15, Math.max(0, sharpe / 1 * 15)); const score = round(consistency + consistencyWf + tradeScore + ddScore + sharpeScore); return { score: clamp(score), verdict: score >= 80 ? 'robust' : score >= 60 ? 'acceptable' : score >= 40 ? 'weak' : 'rejected' } as const }

export function runBacktestStrategy(candles: BacktestCandle[], strategy: BacktestStrategy, options: BacktestOptions = {}) { const settings = { commission: options.commission ?? 0.002, slippage: options.slippage ?? 0.001, initialCapital: options.initialCapital ?? 10000, maxVolumeParticipation: options.maxVolumeParticipation ?? 0.01, stopLossPct: options.stopLossPct ?? 0.02, targetPct: options.targetPct ?? 0.04, maxHoldingBars: options.maxHoldingBars ?? 20 }; if (settings.commission < 0 || settings.slippage < 0 || settings.maxVolumeParticipation <= 0 || settings.maxVolumeParticipation > 0.01) throw new Error('commission_slippage_or_liquidity_limits_invalid'); if (candles.length < 30) return { available: false, reason: 'minimum_30_historical_bars_required', strategy, period: dateRange(candles) }; const scoped = candles.filter(candle => { const date = dateOf(candle, 0); return (!options.from || date >= options.from) && (!options.to || date <= options.to) }); if (scoped.length < 30) return { available: false, reason: 'minimum_30_bars_after_date_filter_required', strategy, period: dateRange(scoped) }; const executed = executeTrades(scoped, strategy, settings), performance = metrics(executed.trades, executed.equity_curve, settings.initialCapital), separation = separationStats(scoped, strategy, settings), walk = walkForward(scoped, strategy, settings), robust = robustness(separation, walk, performance.total_trades, performance.risk_metrics.max_drawdown_pct, performance.risk_adjusted.sharpe_ratio); return { available: performance.total_trades >= 30, rejected_reason: performance.total_trades < 30 ? 'fewer_than_30_trades' : null, strategy, period: dateRange(scoped), ...performance, separation, walk_forward: walk, equity_curve: executed.equity_curve, trades: executed.trades, execution: { signal_bar: 'N', execution_bar: 'N+1_open', commission_pct_round_trip: round(settings.commission * 200, 4), slippage_pct_per_side: round(settings.slippage * 100, 4), max_volume_participation_pct: round(settings.maxVolumeParticipation * 100, 4), rejected_signals: executed.rejected_signals }, bias_checks: { look_ahead: 'passed_signal_uses_bars_0_to_N_and_executes_at_N+1_open', survivorship: 'single-symbol historical test universe was not supplied', corporate_actions: 'depends_on_adjusted_provider_series', liquidity: 'passed_max_1_percent_of_reported_volume' }, robustness_score: robust.score, verdict: robust.verdict, assumptions: { risk_free_rate_annual: 0.04, trading_days_per_year: 252, stop_loss_pct: settings.stopLossPct * 100, target_pct: settings.targetPct * 100, max_holding_bars: settings.maxHoldingBars }, disclaimer: 'نتائج تاريخية افتراضية بعد التكاليف وليست ضماناً للأداء المستقبلي أو توصية استثمارية.' } }

export function runBacktest(candles: BacktestCandle[], options: BacktestOptions & { strategy?: BacktestStrategy } = {}) {
	const strategies = options.strategy ? [options.strategy] : STRATEGIES
	const results = strategies.map(strategy => runBacktestStrategy(candles, strategy, options))
	const scored = results.filter((result): result is typeof result & { performance: unknown; risk_adjusted: { sharpe_ratio: number }; risk_metrics: { max_drawdown_pct: number }; robustness_score: number } => result.available && 'performance' in result)
	const ranked = [...scored].sort((left, right) => right.risk_adjusted.sharpe_ratio - left.risk_adjusted.sharpe_ratio)
	return {
		available: scored.some(result => result.available), symbol: null, backtest_id: `bt_${Date.now()}`,
		strategies: results.map(result => ({ name: result.strategy, results: result })),
		best_strategy: ranked[0]?.strategy ?? null,
		comparison: Object.fromEntries(results.map(result => {
			if (result.available && 'performance' in result) return [result.strategy, { sharpe: result.risk_adjusted.sharpe_ratio, win_rate: result.performance.win_rate, max_dd: result.risk_metrics.max_drawdown_pct, robustness_score: result.robustness_score }]
			return [result.strategy, { available: false, reason: 'rejected_reason' in result ? result.rejected_reason : result.reason }]
		})),
		disclaimer: 'المقارنة تاريخية افتراضية وليست توصية استثمارية.',
	}
}

export { STRATEGIES }
