import { adx, atr, bollingerBands, ema, type CompleteCandle } from './indicators-complete.js'

export type Regime = 'strong_trend_up' | 'strong_trend_down' | 'weak_trend_up' | 'weak_trend_down' | 'range' | 'accumulation' | 'distribution' | 'high_volatility' | 'low_volatility' | 'breakout'
export type RegimeAnalysis = { available: boolean; symbol: string; fetched_at: string; current_regime: { regime: Regime | null; regimeAr: string; confidence: number; duration_bars: number }; characteristics: { adx: number | null; atr_pct: number | null; bollinger_width: number | null; volume_trend: 'expanding' | 'normal' | 'contracting' | 'unavailable' }; regime_weights: Record<string, number>; preferred_indicators: string[]; avoid_indicators: string[]; transition: { detected: boolean; from?: Regime; to?: Regime; progress?: number; confirmed?: boolean; reason?: string }; history: { current_regime_days: number; average_regime_duration: number; regime_changes_60d: number; previous_regime: Regime | null; previous_regime_end: string | null; recent: Array<{ regime: Regime; date: string }> }; trading_context: { recommended_strategy: string; position_sizing: 'reduced' | 'normal' | 'increased'; risk_level: 'low' | 'medium' | 'high'; message_ar: string }; data_quality: { candles: number; minimum_required: number; warnings: string[] } }

type Snapshot = { regime: Regime; adx: number | null; atrPct: number | null; bbWidth: number | null; volumeTrend: 'expanding' | 'normal' | 'contracting' | 'unavailable'; confidence: number }
const MINIMUM_CANDLES = 50
const EPS = 1e-9
const AR: Record<Regime, string> = { strong_trend_up: 'اتجاه صاعد قوي', strong_trend_down: 'اتجاه هابط قوي', weak_trend_up: 'اتجاه صاعد ضعيف', weak_trend_down: 'اتجاه هابط ضعيف', range: 'نطاق جانبي', accumulation: 'تجميع', distribution: 'تصريف', high_volatility: 'تقلب مرتفع', low_volatility: 'تقلب منخفض', breakout: 'اختراق أو ما بعد الاختراق' }
const round = (value: number, digits = 2) => Number.isFinite(value) ? Number(value.toFixed(digits)) : null
const close = (c: CompleteCandle) => c.close
const high = (c: CompleteCandle) => c.high ?? c.close
const low = (c: CompleteCandle) => c.low ?? c.close
const volume = (c: CompleteCandle) => c.volume ?? 0
const date = (c: CompleteCandle, index: number) => c.timestamp == null ? String(index) : new Date(c.timestamp).toISOString().slice(0, 10)
const mean = (values: number[]) => values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0
const pctChange = (a: number, b: number) => ((a - b) / Math.max(Math.abs(b), EPS)) * 100

function obvSlope(candles: CompleteCandle[]) { const values: number[] = [0]; for (let i = 1; i < candles.length; i++) values.push(values.at(-1)! + (close(candles[i]) > close(candles[i - 1]) ? volume(candles[i]) : close(candles[i]) < close(candles[i - 1]) ? -volume(candles[i]) : 0)); const half = Math.floor(values.length / 2); return pctChange(values.at(-1)!, values[half]) }
function detectBreakout(candles: CompleteCandle[]) { if (candles.length < 25) return { detected: false, recent: false, progress: 0 }; const prior = candles.slice(-25, -5), recent = candles.slice(-5), rangeHigh = Math.max(...prior.map(high)), rangeLow = Math.min(...prior.map(low)), latest = recent.at(-1)!, crossed = recent.some(item => high(item) > rangeHigh || low(item) < rangeLow), volumeAverage = mean(prior.map(volume)), spike = volume(latest) > volumeAverage * 1.5; return { detected: crossed && spike, recent: crossed, progress: crossed ? Math.min(1, volume(latest) / Math.max(volumeAverage * 3, EPS)) : 0 } }
function classify(candles: CompleteCandle[]): Snapshot {
	const latest = candles.at(-1)!, current = close(latest), adxValue = adx(candles)?.value ?? null, atrValue = atr(candles)?.value ?? null, atrPct = atrValue == null ? null : (atrValue / Math.max(current, EPS)) * 100, bands = bollingerBands(candles)?.value, bbWidth = bands?.bandwidth == null ? null : bands.bandwidth * 100, priorVolumeAverage = mean(candles.slice(-21, -1).map(volume)), volumeTrend: Snapshot['volumeTrend'] = priorVolumeAverage <= 0 ? 'unavailable' : volume(latest) > priorVolumeAverage * 1.2 ? 'expanding' : volume(latest) < priorVolumeAverage * 0.8 ? 'contracting' : 'normal', ema50 = ema(candles, 50)?.value ?? current, direction = current > ema50 ? 'up' : current < ema50 ? 'down' : 'neutral', breakout = detectBreakout(candles), priorChange = candles.length > 30 ? pctChange(close(candles.at(-16)!), close(candles.at(-31)!)) : 0, obvChange = obvSlope(candles), strong = (adxValue ?? 0) > 30, weak = (adxValue ?? 0) >= 20, range = (adxValue ?? 0) < 20 && (bbWidth ?? 99) < 8 && (bands == null || Math.abs(current - bands.middle) / Math.max(Math.abs(bands.middle), EPS) <= 0.1)
	let regime: Regime = direction === 'up' && strong && volumeTrend === 'expanding' ? 'strong_trend_up' : direction === 'down' && strong && volumeTrend === 'expanding' ? 'strong_trend_down' : breakout.detected ? 'breakout' : (atrPct ?? 0) > 4 || (bbWidth ?? 0) > 8 ? 'high_volatility' : (atrPct ?? 99) < 1.5 && (bbWidth ?? 99) < 3 ? 'low_volatility' : range && priorChange < -3 && obvChange > -5 ? 'accumulation' : range && priorChange > 3 && obvChange < 5 ? 'distribution' : direction === 'up' && weak ? 'weak_trend_up' : direction === 'down' && weak ? 'weak_trend_down' : 'range'
	const rawConfidence = regime === 'breakout' ? 0.55 + breakout.progress * 0.35 : regime.includes('trend') ? 0.55 + Math.min(0.4, Math.abs(adxValue ?? 0) / 100) : regime === 'range' ? 0.6 : 0.65; return { regime, adx: adxValue, atrPct, bbWidth, volumeTrend, confidence: Math.min(0.95, round(rawConfidence, 2) ?? 0.5) }
}
const weightsFor = (regime: Regime) => { const base = { trend: 1, momentum: 1, mean_reversion: 1, volume: 1, volatility: 1, wyckoff: 1, vsa: 1, pattern: 1 }; if (regime === 'strong_trend_up' || regime === 'strong_trend_down' || regime === 'weak_trend_up' || regime === 'weak_trend_down') Object.assign(base, { trend: 1.5, momentum: 1.2, mean_reversion: 0.5, oscillators: 0.8 }); else if (regime === 'range') Object.assign(base, { mean_reversion: 1.5, oscillators: 1.3, trend: 0.6, macd: 0.7 }); else if (regime === 'high_volatility') Object.assign(base, { volatility: 1.5, breakout: 1.4, mean_reversion: 0.5 }); else if (regime === 'low_volatility') Object.assign(base, { breakout_anticipation: 1.2, range: 1.3, volatility: 0.7 }); else if (regime === 'accumulation' || regime === 'distribution') Object.assign(base, { wyckoff: 1.5, vsa: 1.4, volume: 1.3, trend: 0.5 }); else if (regime === 'breakout') Object.assign(base, { momentum: 1.5, volume: 1.4, trend: 1.3, mean_reversion: 0.4 }); return base }
function recommendation(regime: Regime) { if (regime.includes('trend')) return { strategy: 'trend_following', position: 'normal' as const, risk: 'low' as const, preferred: ['MACD', 'EMA', 'ADX', 'Supertrend'], avoid: ['RSI_divergence', 'mean_reversion', 'contrarian'] }; if (regime === 'range' || regime === 'accumulation' || regime === 'distribution') return { strategy: 'range_trading', position: 'normal' as const, risk: 'medium' as const, preferred: ['RSI', 'Stochastic', 'Support/Resistance', 'Wyckoff'], avoid: ['trend_following', 'breakout_anticipation'] }; if (regime === 'high_volatility' || regime === 'breakout') return { strategy: 'breakout_momentum', position: 'reduced' as const, risk: 'high' as const, preferred: ['ATR', 'Volume', 'MACD', 'Bollinger Bands'], avoid: ['mean_reversion', 'tight_stops'] }; return { strategy: 'volatility_contraction', position: 'increased' as const, risk: 'medium' as const, preferred: ['Bollinger Bands', 'ATR', 'Volume'], avoid: ['overtrading'] } }
function transition(previous: Snapshot | null, current: Snapshot, candles: CompleteCandle[]) { if (!previous || previous.regime === current.regime) return { detected: false as const }; const reason = previous.regime === 'range' && current.regime === 'breakout' ? 'Bollinger expansion + volume spike' : previous.regime.includes('trend') && current.regime === 'range' ? 'ADX falling below trend threshold' : previous.regime === 'low_volatility' && current.regime === 'high_volatility' ? 'ATR expansion' : 'Regime characteristics changed'; return { detected: true as const, from: previous.regime, to: current.regime, progress: Math.min(1, Math.abs((current.adx ?? 0) - (previous.adx ?? 0)) / 30 + Math.abs((current.atrPct ?? 0) - (previous.atrPct ?? 0)) / 8), confirmed: candles.length >= 100, reason } }

export function analyzeMarketRegime(symbol: string, candles: CompleteCandle[]): RegimeAnalysis {
	if (candles.length < MINIMUM_CANDLES) return { available: false, symbol, fetched_at: new Date().toISOString(), current_regime: { regime: null, regimeAr: 'غير متاح', confidence: 0, duration_bars: 0 }, characteristics: { adx: null, atr_pct: null, bollinger_width: null, volume_trend: 'unavailable' }, regime_weights: {}, preferred_indicators: [], avoid_indicators: [], transition: { detected: false }, history: { current_regime_days: 0, average_regime_duration: 0, regime_changes_60d: 0, previous_regime: null, previous_regime_end: null, recent: [] }, trading_context: { recommended_strategy: 'insufficient_data', position_sizing: 'reduced', risk_level: 'high', message_ar: 'لا توجد شموع كافية لتصنيف بيئة السوق' }, data_quality: { candles: candles.length, minimum_required: MINIMUM_CANDLES, warnings: ['At least 50 candles are required for regime detection.'] } }
	const input = candles.slice(-200), current = classify(input), previous = input.length >= 80 ? classify(input.slice(0, -20)) : null, recent: Array<{ regime: Regime; date: string }> = []; for (let i = Math.max(50, input.length - 50); i <= input.length; i++) { const slice = input.slice(0, i); const snapshot = slice.length >= 50 ? classify(slice) : current; recent.push({ regime: snapshot.regime, date: date(input[Math.min(i - 1, input.length - 1)], Math.min(i - 1, input.length - 1)) }) }
	const changes = recent.filter((item, index) => index > 0 && item.regime !== recent[index - 1].regime).length, runs: number[] = []; let run = 1; for (let i = 1; i < recent.length; i++) { if (recent[i].regime === recent[i - 1].regime) run++; else { runs.push(run); run = 1 } } runs.push(run); const context = recommendation(current.regime), currentDuration = recent.slice().reverse().findIndex(item => item.regime !== current.regime); const duration = currentDuration < 0 ? recent.length : currentDuration + 1, message = `السوق في ${AR[current.regime]} — الاستراتيجية المفضلة: ${context.strategy}`; return { available: true, symbol, fetched_at: new Date().toISOString(), current_regime: { regime: current.regime, regimeAr: AR[current.regime], confidence: current.confidence, duration_bars: duration }, characteristics: { adx: round(current.adx ?? NaN), atr_pct: round(current.atrPct ?? NaN), bollinger_width: round(current.bbWidth ?? NaN), volume_trend: current.volumeTrend }, regime_weights: weightsFor(current.regime), preferred_indicators: context.preferred, avoid_indicators: context.avoid, transition: transition(previous, current, input), history: { current_regime_days: duration, average_regime_duration: Math.round(mean(runs)), regime_changes_60d: changes, previous_regime: previous?.regime ?? null, previous_regime_end: previous ? date(input[Math.max(0, input.length - 21)], Math.max(0, input.length - 21)) : null, recent }, trading_context: { recommended_strategy: context.strategy, position_sizing: context.position, risk_level: context.risk, message_ar: message }, data_quality: { candles: candles.length, minimum_required: MINIMUM_CANDLES, warnings: candles.some(candle => candle.volume == null) ? ['Some candles lack volume; volume character is conservative.'] : [] } }
}

export const marketRegimeMetadata = { regimes: ['strong_trend_up', 'strong_trend_down', 'weak_trend_up', 'weak_trend_down', 'range', 'accumulation', 'distribution', 'high_volatility', 'low_volatility', 'breakout'] as const, minimumCandles: MINIMUM_CANDLES }
