import { atr, bollingerBands, ema, macd, rsi, stochastic as stochasticIndicator, type CompleteCandle } from './indicators-complete.js'

export const TIMEFRAMES = ['1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w', '1M'] as const
export type Timeframe = typeof TIMEFRAMES[number]
export type TrendDirection = 'up' | 'down' | 'neutral'
export type MTFSignal = 'STRONG_BUY' | 'BUY' | 'NEUTRAL' | 'SELL' | 'STRONG_SELL'
export type FrameAnalysis = {
	timeframe: Timeframe
	timeframeAr: string
	trend: { direction: TrendDirection; strength: number; structure: 'HH_HL' | 'LH_LL' | 'mixed'; bos: boolean; choch: boolean; reason: string }
	momentum: { rsi: number | null; macd: 'bullish' | 'bearish' | 'neutral'; stoch: 'overbought' | 'oversold' | 'neutral'; direction: TrendDirection; strength: number }
	volatility: { atr: number | null; atr_pct: number | null; bollinger_width: number | null; level: 'low' | 'normal' | 'high' }
	signal: { type: MTFSignal; strength: number; confidence: number; reasons: string[] }
	data_quality: { available: boolean; candles_count: number; source: string; reason?: string }
}
export type MultiTimeframeAnalysis = {
	symbol: string
	market: string
	fetched_at: string
	matrix: Partial<Record<Timeframe, FrameAnalysis>>
	alignment: { score: number; category: 'STRONG_ALIGNMENT' | 'MODERATE_ALIGNMENT' | 'WEAK_ALIGNMENT' | 'CONFLICTED'; bullish_timeframes: number; bearish_timeframes: number; neutral_timeframes: number; dominant_direction: TrendDirection; conflict_level: 'low' | 'medium' | 'high' }
	top_down: { macro_trend: { timeframe: Timeframe; direction: TrendDirection }; medium_trend: { timeframe: Timeframe; direction: TrendDirection }; entry_trend: { timeframe: Timeframe; direction: TrendDirection }; confluence: boolean; recommended_entry_timeframe: Timeframe | null; reason: string }
	divergences: Array<{ timeframe: Timeframe; type: 'regular_bullish' | 'regular_bearish' | 'hidden_bullish' | 'hidden_bearish'; indicator: 'RSI' | 'MACD' | 'OBV'; strength: number; price_points: [number, number]; indicator_points: [number, number] }>
	summary: { overall_signal: MTFSignal; confidence: number; best_entry_timeframe: Timeframe | null; risk_level: 'low' | 'medium' | 'high'; key_message: string }
}

const AR: Record<Timeframe, string> = { '1m': 'دقيقة', '5m': '5 دقائق', '15m': '15 دقيقة', '30m': '30 دقيقة', '1h': 'ساعة', '4h': '4 ساعات', '1d': 'يومي', '1w': 'أسبوعي', '1M': 'شهري' }
const MINIMUM_CANDLES = 30
const close = (c: CompleteCandle) => c.close
const high = (c: CompleteCandle) => c.high ?? c.close
const low = (c: CompleteCandle) => c.low ?? c.close
const round = (value: number, digits = 2) => Number.isFinite(value) ? Number(value.toFixed(digits)) : null
const directionFrom = (value: number, threshold: number): TrendDirection => value > threshold ? 'up' : value < -threshold ? 'down' : 'neutral'
function structure(candles: CompleteCandle[]): 'HH_HL' | 'LH_LL' | 'mixed' { const half = Math.floor(candles.length / 2), first = candles.slice(0, half), second = candles.slice(half), firstHigh = Math.max(...first.map(high)), secondHigh = Math.max(...second.map(high)), firstLow = Math.min(...first.map(low)), secondLow = Math.min(...second.map(low)); return secondHigh > firstHigh && secondLow > firstLow ? 'HH_HL' : secondHigh < firstHigh && secondLow < firstLow ? 'LH_LL' : 'mixed' }
function frameAnalysis(timeframe: Timeframe, candles: CompleteCandle[] | undefined, source: string): FrameAnalysis {
	if (!candles || candles.length < MINIMUM_CANDLES) return { timeframe, timeframeAr: AR[timeframe], trend: { direction: 'neutral', strength: 0, structure: 'mixed', bos: false, choch: false, reason: 'بيانات غير كافية لهذا الفريم' }, momentum: { rsi: null, macd: 'neutral', stoch: 'neutral', direction: 'neutral', strength: 0 }, volatility: { atr: null, atr_pct: null, bollinger_width: null, level: 'normal' }, signal: { type: 'NEUTRAL', strength: 0, confidence: 0, reasons: ['أقل من 30 شمعة متاحة'] }, data_quality: { available: false, candles_count: candles?.length ?? 0, source, reason: 'At least 30 candles are required.' } }
	const current = close(candles.at(-1)!), ema20 = ema(candles, 20)?.value ?? current, ema50 = ema(candles, 50)?.value ?? current, change = close(candles.at(-1)!) - close(candles.at(-11)!), trendDirection = directionFrom(change, current * 0.005), struct = structure(candles), trend = trendDirection === 'neutral' ? (current > ema20 && ema20 >= ema50 ? 'up' : current < ema20 && ema20 <= ema50 ? 'down' : 'neutral') : trendDirection, trendStrength = Math.min(100, Math.round((Math.abs(current - ema20) / Math.max(current, 1)) * 1000 + (Math.abs(change) / Math.max(current, 1)) * 500)), rsiValue = rsi(candles)?.value ?? null, macdValue = macd(candles)?.value, stochasticValue = stochasticIndicator(candles)?.value ?? null, atrValue = atr(candles)?.value ?? null, bands = bollingerBands(candles)?.value, atrPct = atrValue == null ? null : (atrValue / Math.max(current, 1)) * 100, bbWidth = bands?.bandwidth ?? null
	const momentumDirection: TrendDirection = (macdValue && macdValue.histogram > 0) || (rsiValue != null && rsiValue > 55) ? 'up' : (macdValue && macdValue.histogram < 0) || (rsiValue != null && rsiValue < 45) ? 'down' : 'neutral'; const momentumStrength = Math.min(100, Math.round(Math.abs((rsiValue ?? 50) - 50) * 2 + Math.abs(macdValue?.histogram ?? 0) / Math.max(current, 1) * 1000)); const stochState = stochasticValue == null ? 'neutral' : stochasticValue >= 80 ? 'overbought' : stochasticValue <= 20 ? 'oversold' : 'neutral'; const volatilityLevel = atrPct == null ? 'normal' : atrPct > 4 ? 'high' : atrPct < 1 ? 'low' : 'normal'; const score = (trend === 'up' ? 1 : trend === 'down' ? -1 : 0) + (momentumDirection === 'up' ? 1 : momentumDirection === 'down' ? -1 : 0) + (rsiValue != null && rsiValue > 70 ? -0.5 : rsiValue != null && rsiValue < 30 ? 0.5 : 0); const signal = score >= 1.8 ? 'STRONG_BUY' : score >= 0.7 ? 'BUY' : score <= -1.8 ? 'STRONG_SELL' : score <= -0.7 ? 'SELL' : 'NEUTRAL'; const reasons = [trend === 'up' ? 'Trend up' : trend === 'down' ? 'Trend down' : 'Trend neutral', rsiValue == null ? 'RSI unavailable' : `RSI ${Math.round(rsiValue)}`, macdValue == null ? 'MACD unavailable' : `MACD ${macdValue.histogram >= 0 ? 'bullish' : 'bearish'}`]; return { timeframe, timeframeAr: AR[timeframe], trend: { direction: trend, strength: trendStrength, structure: struct, bos: struct !== 'mixed' && trend !== 'neutral', choch: struct === 'mixed' && trend !== 'neutral', reason: current >= ema20 ? 'السعر فوق EMA20' : 'السعر تحت EMA20' }, momentum: { rsi: rsiValue == null ? null : round(rsiValue), macd: macdValue == null ? 'neutral' : macdValue.histogram > 0 ? 'bullish' : macdValue.histogram < 0 ? 'bearish' : 'neutral', stoch: stochState, direction: momentumDirection, strength: momentumStrength }, volatility: { atr: atrValue == null ? null : round(atrValue), atr_pct: atrPct == null ? null : round(atrPct), bollinger_width: bbWidth == null ? null : round(bbWidth), level: volatilityLevel }, signal: { type: signal, strength: Math.min(100, Math.round(Math.abs(score) / 2 * 100)), confidence: round(Math.min(0.99, 0.5 + Math.abs(score) * 0.15), 2) ?? 0, reasons }, data_quality: { available: true, candles_count: candles.length, source } }
}
function alignment(frames: FrameAnalysis[]): MultiTimeframeAnalysis['alignment'] { const bullish = frames.filter(frame => frame.trend.direction === 'up').length, bearish = frames.filter(frame => frame.trend.direction === 'down').length, neutral = frames.length - bullish - bearish, dominant: TrendDirection = bullish > bearish ? 'up' : bearish > bullish ? 'down' : 'neutral', score = frames.length ? Math.max(bullish, bearish) / frames.length : 0, category = score > 0.75 ? 'STRONG_ALIGNMENT' : score >= 0.55 ? 'MODERATE_ALIGNMENT' : score >= 0.35 ? 'WEAK_ALIGNMENT' : 'CONFLICTED', conflict_level = bullish > 0 && bearish > 0 ? Math.abs(bullish - bearish) <= 1 ? 'high' : 'medium' : 'low'; return { score: round(score, 2) ?? 0, category, bullish_timeframes: bullish, bearish_timeframes: bearish, neutral_timeframes: neutral, dominant_direction: dominant, conflict_level } }
function divergence(timeframe: Timeframe, candles: CompleteCandle[]) { if (candles.length < 60) return []; const half = Math.floor(candles.length / 2), first = candles.slice(0, half), second = candles.slice(half), priceFirst = close(first.at(-1)!), priceSecond = close(second.at(-1)!), firstRsi = rsi(first)?.value ?? 50, secondRsi = rsi(second)?.value ?? 50, priceLower = priceSecond < priceFirst, priceHigher = priceSecond > priceFirst, rsiHigher = secondRsi > firstRsi + 3, rsiLower = secondRsi < firstRsi - 3, type: 'regular_bullish' | 'regular_bearish' | null = priceLower && rsiHigher ? 'regular_bullish' : priceHigher && rsiLower ? 'regular_bearish' : null; if (!type) return []; return [{ timeframe, type, indicator: 'RSI' as const, strength: Math.min(0.95, round(Math.abs(secondRsi - firstRsi) / 100 + 0.5, 2) ?? 0.5), price_points: [round(priceFirst)!, round(priceSecond)!] as [number, number], indicator_points: [round(firstRsi)!, round(secondRsi)!] as [number, number] }] }

export function analyzeMultiTimeframe(symbol: string, market: string, candlesByTimeframe: Partial<Record<Timeframe, CompleteCandle[] | undefined>>, source = 'provided'): MultiTimeframeAnalysis {
	const matrix: Partial<Record<Timeframe, FrameAnalysis>> = {}; for (const timeframe of TIMEFRAMES) matrix[timeframe] = frameAnalysis(timeframe, candlesByTimeframe[timeframe], source); const frames = Object.values(matrix).filter((frame): frame is FrameAnalysis => frame != null && frame.data_quality.available), align = alignment(frames), macro = matrix['1M']?.data_quality.available ? matrix['1M'] : matrix['1w']!, medium = matrix['1d']?.data_quality.available ? matrix['1d'] : matrix['4h']!, entry = matrix['4h']?.data_quality.available ? matrix['4h'] : matrix['1h']!, confluence = !!macro?.data_quality.available && !!medium?.data_quality.available && !!entry?.data_quality.available && macro.trend.direction === medium.trend.direction && medium.trend.direction === entry.trend.direction, recommended = confluence ? entry.timeframe : null, divergences = frames.flatMap(frame => divergence(frame.timeframe, candlesByTimeframe[frame.timeframe]!)), overallSignal: MTFSignal = align.dominant_direction === 'up' ? align.score > 0.75 ? 'STRONG_BUY' : 'BUY' : align.dominant_direction === 'down' ? align.score > 0.75 ? 'STRONG_SELL' : 'SELL' : 'NEUTRAL', risk = align.conflict_level === 'high' ? 'high' : align.score < 0.55 ? 'medium' : 'low'; return { symbol, market, fetched_at: new Date().toISOString(), matrix, alignment: align, top_down: { macro_trend: { timeframe: macro?.timeframe ?? '1w', direction: macro?.trend.direction ?? 'neutral' }, medium_trend: { timeframe: medium?.timeframe ?? '1d', direction: medium?.trend.direction ?? 'neutral' }, entry_trend: { timeframe: entry?.timeframe ?? '4h', direction: entry?.trend.direction ?? 'neutral' }, confluence, recommended_entry_timeframe: recommended, reason: confluence ? 'الفريمات الرئيسية متوافقة' : 'يوجد اختلاف أو نقص في الفريمات الرئيسية' }, divergences, summary: { overall_signal: overallSignal, confidence: round(Math.min(0.99, align.score * 0.8 + (confluence ? 0.2 : 0)), 2) ?? 0, best_entry_timeframe: recommended, risk_level: risk, key_message: `${align.bullish_timeframes} فريم صاعد، ${align.bearish_timeframes} فريم هابط` } }
}

export const multiTimeframeMetadata = { timeframes: TIMEFRAMES, minimumCandles: MINIMUM_CANDLES }
