export const educationCatalog = [
	{
		title: 'أساسيات التحليل الفني',
		titleEn: 'Technical Analysis Basics',
		description: 'مدخل عملي لفهم الاتجاهات والدعم والمقاومة وإدارة القرار.',
		level: 'BEGINNER',
		category: 'TECHNICAL',
		duration: 90,
		price: 0,
		isFree: true,
	},
	{
		title: 'قراءة الشموع اليابانية',
		titleEn: 'Japanese Candlesticks',
		description: 'تعلم قراءة الشموع والنماذج الانعكاسية والاستمرارية.',
		level: 'BEGINNER',
		category: 'TECHNICAL',
		duration: 75,
		price: 0,
		isFree: true,
	},
	{
		title: 'Elliott Wave من الصفر',
		titleEn: 'Elliott Wave from Zero',
		description: 'منهج تعليمي لفهم الموجات الدافعة والتصحيحية دون وعود تنبؤية.',
		level: 'INTERMEDIATE',
		category: 'TECHNICAL',
		duration: 150,
		price: 19,
		isFree: false,
	},
	{
		title: 'Gann Analysis الاحترافي',
		titleEn: 'Professional Gann Analysis',
		description: 'الزوايا والدورات والمستويات مع تطبيقات تعليمية.',
		level: 'ADVANCED',
		category: 'TECHNICAL',
		duration: 180,
		price: 29,
		isFree: false,
	},
	{
		title: 'إدارة المخاطر',
		titleEn: 'Risk Management',
		description: 'حجم الصفقة ووقف الخسارة ونسبة المخاطرة إلى العائد.',
		level: 'INTERMEDIATE',
		category: 'RISK',
		duration: 100,
		price: 19,
		isFree: false,
	},
	{
		title: 'التحليل الأساسي',
		titleEn: 'Fundamental Analysis',
		description: 'قراءة القوائم المالية والمؤشرات الأساسية بطريقة عملية.',
		level: 'INTERMEDIATE',
		category: 'FUNDAMENTAL',
		duration: 140,
		price: 19,
		isFree: false,
	},
	{
		title: 'التداول النفسي',
		titleEn: 'Trading Psychology',
		description: 'بناء الانضباط وتقليل التحيزات والانفعالات.',
		level: 'BEGINNER',
		category: 'RISK',
		duration: 80,
		price: 15,
		isFree: false,
	},
	{
		title: 'التوافق مع الشريعة',
		titleEn: 'Shariah Compliance',
		description: 'مفاهيم الفحص الشرعي والتطهير مع تنبيه تعليمي.',
		level: 'INTERMEDIATE',
		category: 'SHARIAH',
		duration: 95,
		price: 15,
		isFree: false,
	},
	{
		title: 'استخدام AI في التداول',
		titleEn: 'AI for Trading',
		description: 'فهم استخدام أدوات الذكاء الاصطناعي والتحقق من مخرجاتها.',
		level: 'ADVANCED',
		category: 'TECHNICAL',
		duration: 120,
		price: 29,
		isFree: false,
	},
	{
		title: 'استراتيجيات الربح',
		titleEn: 'Profit Strategies',
		description: 'تصميم خطة تداول واختبارها ومراجعتها تاريخياً.',
		level: 'ADVANCED',
		category: 'RISK',
		duration: 160,
		price: 39,
		isFree: false,
	},
] as const

export const lessonTemplates = (courseTitle: string) => [
	{
		title: `مقدمة: ${courseTitle}`,
		content: `درس تمهيدي في ${courseTitle}. هذا المحتوى تعليمي وليس توصية استثمارية.`,
		duration: 15,
		order: 1,
	},
	{
		title: 'المفاهيم الأساسية',
		content: 'شرح المفاهيم والأمثلة العملية مع أسئلة مراجعة.',
		duration: 25,
		order: 2,
	},
	{
		title: 'تطبيق عملي',
		content: 'تطبيق تدريبي على بيانات تاريخية مع توضيح حدود المنهج.',
		duration: 30,
		order: 3,
	},
]

export type EducationCatalogItem = (typeof educationCatalog)[number]
