ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "tier" TEXT NOT NULL DEFAULT 'FREE';
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "dailyLimit" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "monthlyLimit" INTEGER NOT NULL DEFAULT 3000;
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "api_keys" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
CREATE TABLE IF NOT EXISTS "api_usage_logs" ("id" TEXT NOT NULL,"apiKeyId" TEXT NOT NULL,"endpoint" TEXT NOT NULL,"method" TEXT NOT NULL,"statusCode" INTEGER NOT NULL,"latencyMs" INTEGER NOT NULL,"ipAddress" TEXT,"userAgent" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "api_usage_logs_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "api_usage_logs_apiKeyId_createdAt_idx" ON "api_usage_logs"("apiKeyId","createdAt");
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='api_usage_logs_apiKeyId_fkey') THEN ALTER TABLE "api_usage_logs" ADD CONSTRAINT "api_usage_logs_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "api_keys"("id") ON DELETE CASCADE ON UPDATE CASCADE; END IF; END $$;
CREATE TABLE IF NOT EXISTS "api_subscriptions" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"tier" TEXT NOT NULL DEFAULT 'FREE',"monthlyPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,"startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"endsAt" TIMESTAMP(3),"autoRenew" BOOLEAN NOT NULL DEFAULT false,"paymentMethod" TEXT,"status" TEXT NOT NULL DEFAULT 'ACTIVE',CONSTRAINT "api_subscriptions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "api_subscriptions_userId_key" ON "api_subscriptions"("userId");
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='api_subscriptions_userId_fkey') THEN ALTER TABLE "api_subscriptions" ADD CONSTRAINT "api_subscriptions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE; END IF; END $$;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "experience" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "credentials" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "verificationDate" TIMESTAMP(3);
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "subscriptionPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "totalSubscribers" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "totalRevenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "analyst_profiles" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "analyst_subscriptions" ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "analyst_subscriptions" ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "analyst_subscriptions" ADD COLUMN IF NOT EXISTS "endsAt" TIMESTAMP(3);
CREATE TABLE IF NOT EXISTS "analyst_posts" ("id" TEXT NOT NULL,"analystId" TEXT NOT NULL,"symbol" TEXT,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"content" TEXT NOT NULL,"charts" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"sentiment" TEXT,"isPremium" BOOLEAN NOT NULL DEFAULT false,"views" INTEGER NOT NULL DEFAULT 0,"likes" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "analyst_posts_pkey" PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "analyst_posts_analystId_createdAt_idx" ON "analyst_posts"("analystId","createdAt");
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='analyst_posts_analystId_fkey') THEN ALTER TABLE "analyst_posts" ADD CONSTRAINT "analyst_posts_analystId_fkey" FOREIGN KEY ("analystId") REFERENCES "analyst_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE; END IF; END $$;
CREATE TABLE IF NOT EXISTS "whatsapp_subscriptions" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"phoneNumber" TEXT NOT NULL,"isVerified" BOOLEAN NOT NULL DEFAULT false,"verificationCode" TEXT,"alertTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "whatsapp_subscriptions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "whatsapp_subscriptions_userId_key" ON "whatsapp_subscriptions"("userId");
CREATE TABLE IF NOT EXISTS "telegram_subscriptions" ("id" TEXT NOT NULL,"userId" TEXT,"chatId" TEXT NOT NULL,"username" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"alertTypes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "telegram_subscriptions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "telegram_subscriptions_userId_key" ON "telegram_subscriptions"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "telegram_subscriptions_chatId_key" ON "telegram_subscriptions"("chatId");
