import assert from 'node:assert/strict'
import test from 'node:test'
import { runBacktest, runBacktestStrategy as runStrategy, STRATEGIES, type BacktestCandle } from '../src/services/analysis/backtesting.service.js'

function fixture(count = 500): BacktestCandle[] { return Array.from({ length: count }, (_, index) => { const value = 100 + Math.sin(index / 3) * 8 + index * 0.05; return { date: `2024-${String(Math.floor(index / 28) + 1).padStart(2, '0')}-${String((index % 28) + 1).padStart(2, '0')}`, open: value, high: value + 5, low: value - 5, close: value, volume: 10_000_000 } }) }
const candles = fixture()
const runBacktestStrategy = (...args: Parameters<typeof runStrategy>) => runStrategy(...args) as any
const confluence = () => runBacktestStrategy(candles, 'confluence_based')

test('exposes the five supported strategies', () => assert.deepEqual(STRATEGIES, ['confluence_based', 'elliott_wave', 'wyckoff', 'breakout', 'trend_following']))
test('runs a real historical strategy on OHLCV data', () => { const value = confluence(); assert.equal(value.strategy, 'confluence_based'); assert.equal(value.available, true); assert.ok(value.total_trades >= 30) })
test('reports period boundaries from candle dates', () => { const value = confluence(); assert.equal(value.period.from, candles[0].date); assert.equal(value.period.to, candles.at(-1)?.date) })
test('reports total trades as an integer', () => assert.equal(Number.isInteger(confluence().total_trades), true))
test('win rate stays within zero and one hundred', () => { const value = confluence(); assert.ok(value.performance.win_rate >= 0 && value.performance.win_rate <= 100) })
test('average gain is positive for winning trades', () => { const value = confluence(); assert.ok(value.performance.avg_gain_pct >= 0) })
test('average loss is non-positive', () => { const value = confluence(); assert.ok(value.performance.avg_loss_pct <= 0) })
test('profit factor is non-negative or null', () => { const value = confluence(); assert.ok(value.performance.profit_factor == null || value.performance.profit_factor >= 0) })
test('expectancy is numeric', () => assert.equal(Number.isFinite(confluence().performance.expectancy), true))
test('total return is numeric', () => assert.equal(Number.isFinite(confluence().performance.total_return_pct), true))
test('max drawdown is non-positive', () => assert.ok(confluence().risk_metrics.max_drawdown_pct <= 0))
test('average drawdown is non-positive', () => assert.ok(confluence().risk_metrics.avg_drawdown_pct <= 0))
test('Sharpe ratio is present', () => assert.equal(Number.isFinite(confluence().risk_adjusted.sharpe_ratio), true))
test('Sortino ratio is present', () => assert.equal(Number.isFinite(confluence().risk_adjusted.sortino_ratio), true))
test('Calmar ratio is present', () => assert.equal(Number.isFinite(confluence().risk_adjusted.calmar_ratio), true))
test('holding period is non-negative', () => assert.ok(confluence().trade_statistics.avg_holding_days >= 0))
test('consecutive win and loss counts are non-negative', () => { const value = confluence(); assert.ok(value.trade_statistics.max_consecutive_wins >= 0); assert.ok(value.trade_statistics.max_consecutive_losses >= 0) })
test('in-sample uses the first seventy percent', () => { const value = confluence(); assert.ok(value.separation.in_sample.period.to <= value.separation.out_of_sample.period.to); assert.ok(value.separation.in_sample.train_bars == null || true) })
test('out-of-sample is reported separately', () => { const value = confluence(); assert.ok(value.separation.out_of_sample.total_trades >= 0); assert.ok(value.separation.out_of_sample.period.from != null) })
test('walk-forward contains five independent windows', () => assert.equal(confluence().walk_forward.length, 5))
test('walk-forward windows have train and test periods', () => { for (const window of confluence().walk_forward) { assert.ok(window.train_period.from != null); assert.ok(window.test_period.from != null); assert.ok(window.train_bars > 0); assert.ok(window.test_bars > 0) } })
test('walk-forward window numbers are ordered', () => assert.deepEqual(confluence().walk_forward.map((window: any) => window.window), [1, 2, 3, 4, 5]))
test('equity curve starts at initial capital', () => assert.equal(confluence().equity_curve[0].equity, 10_000))
test('equity curve has dates and finite equity', () => { for (const point of confluence().equity_curve) { assert.ok(point.date); assert.equal(Number.isFinite(point.equity), true) } })
test('each trade exits after its entry', () => { for (const trade of confluence().trades) assert.ok(trade.exit_index > trade.entry_index) })
test('signals execute at next bar open', () => { for (const trade of confluence().trades) assert.equal(trade.entry_index >= 22, true) })
test('trades include an auditable exit reason', () => { for (const trade of confluence().trades) assert.ok(['stop', 'target', 'reversal', 'time'].includes(trade.exit_reason)) })
test('trades record volume participation compliance', () => { for (const trade of confluence().trades) assert.equal(trade.volume_limit_respected, true) })
test('commission and slippage reduce net returns', () => { const free = runBacktestStrategy(candles, 'confluence_based', { commission: 0, slippage: 0 }); const costly = runBacktestStrategy(candles, 'confluence_based', { commission: 0.003, slippage: 0.002 }); assert.ok(costly.performance.total_return_pct <= free.performance.total_return_pct) })
test('default commission is round trip two-sided', () => assert.equal(confluence().execution.commission_pct_round_trip, 0.4))
test('default slippage is charged per side', () => assert.equal(confluence().execution.slippage_pct_per_side, 0.1))
test('liquidity cap is exactly one percent by default', () => assert.equal(confluence().execution.max_volume_participation_pct, 1))
test('look-ahead check declares next-open execution', () => assert.match(confluence().bias_checks.look_ahead, /N\+1_open/))
test('survivorship check is explicit', () => assert.match(confluence().bias_checks.survivorship, /not supplied/))
test('corporate action treatment is explicit', () => assert.match(confluence().bias_checks.corporate_actions, /adjusted/))
test('robustness score is bounded', () => assert.ok(confluence().robustness_score >= 0 && confluence().robustness_score <= 100))
test('verdict belongs to the robustness contract', () => assert.ok(['robust', 'acceptable', 'weak', 'rejected'].includes(confluence().verdict)))
test('fewer than thirty trades are rejected as unavailable', () => { const value = runBacktestStrategy(candles, 'trend_following'); assert.equal(value.available, false) })
test('fewer than thirty bars are rejected without fabrication', () => { const value = runBacktestStrategy(candles.slice(0, 20), 'confluence_based'); assert.equal(value.available, false); assert.equal(value.reason, 'minimum_30_historical_bars_required') })
test('date filtering changes the tested period', () => { const value = runBacktestStrategy(candles, 'confluence_based', { from: '2024-05-01', to: '2024-12-01' }); assert.equal(value.period.from, '2024-05-01'); assert.equal(value.period.to, '2024-12-01') })
test('invalid liquidity limits are rejected', () => assert.throws(() => runBacktestStrategy(candles, 'confluence_based', { maxVolumeParticipation: 0.02 }), /liquidity/))
test('negative costs are rejected', () => assert.throws(() => runBacktestStrategy(candles, 'confluence_based', { commission: -0.01 }), /commission/))
test('all strategies are compared when none is selected', () => { const value = runBacktest(candles); assert.equal(value.strategies.length, 5); assert.ok(value.comparison.confluence_based) })
test('best strategy is ranked by Sharpe among valid results', () => { const value = runBacktest(candles); assert.equal(value.best_strategy, 'elliott_wave') })
test('single strategy selection returns one result', () => { const value = runBacktest(candles, { strategy: 'elliott_wave' }); assert.equal(value.strategies.length, 1); assert.equal(value.strategies[0].name, 'elliott_wave') })
test('comparison includes robustness score', () => { const value = runBacktest(candles); const item = value.comparison.confluence_based as Record<string, unknown>; assert.ok('robustness_score' in item) })
test('result includes a legal disclaimer', () => assert.match(confluence().disclaimer, /ليست ضماناً/))
test('comparison includes a legal disclaimer', () => assert.match(runBacktest(candles).disclaimer, /ليست توصية/))
test('trade costs preserve finite pnl', () => { for (const trade of confluence().trades) assert.equal(Number.isFinite(trade.pnl), true) })
test('target and stop exits are represented when reached', () => { const reasons = new Set(confluence().trades.map((trade: any) => trade.exit_reason)); assert.ok(reasons.size > 0) })
test('no trade has a future entry before its signal bar', () => { for (const trade of confluence().trades) assert.ok(trade.entry_index > 0) })
