import assert from 'node:assert/strict'
import test from 'node:test'
import { analyzeClassicalPatterns, classicalPatternMetadata, type ClassicalCandle, type ClassicalPattern } from '../src/services/analysis/classical-patterns.service.js'

function c(index: number, close: number, volume = 1000, spread = 1): ClassicalCandle { return { open: close - 0.2, high: close + spread, low: close - spread, close, volume, timestamp: `2026-08-${String((index % 28) + 1).padStart(2, '0')}` } }
function flat(count = 60, price = 100): ClassicalCandle[] { return Array.from({ length: count }, (_, i) => c(i, price)) }
function extremaSeries(values: number[]): ClassicalCandle[] { return values.map((value, i) => c(i, value, 1000, 0.8)) }
function triangle(type: 'ascending' | 'descending' | 'symmetrical'): ClassicalCandle[] {
	const values = flat(60), start = 35
	for (let cycle = 0; cycle < 5; cycle++) { const upper = type === 'ascending' ? 120 : type === 'descending' ? 130 - cycle * 4 : 130 - cycle * 4; const lower = type === 'ascending' ? 90 + cycle * 5 : type === 'descending' ? 90 : 90 + cycle * 5; const i = start + cycle * 5; values[i] = c(i, 105); values[i + 1] = c(i + 1, upper, 800); values[i + 2] = c(i + 2, 105); values[i + 3] = c(i + 3, lower, 800); values[i + 4] = c(i + 4, 105) }
	return values
}
function flag(bullish: boolean): ClassicalCandle[] { const values = flat(30); for (let i = 14; i <= 22; i++) values[i] = c(i, bullish ? 100 + (i - 13) * 3 : 160 - (i - 13) * 3, 1600, 1.5); for (let i = 23; i < 30; i++) values[i] = c(i, bullish ? 127 - (i - 22) * 0.8 : 133 + (i - 22) * 0.8, 700, 0.8); return values }

function assertPattern(pattern: ClassicalPattern | undefined, name: string) { assert.ok(pattern, `${name} was not detected`); assert.equal(pattern!.name, name); assert.ok(pattern!.confidence > 0 && pattern!.confidence <= 1); assert.ok(['forming', 'confirmed', 'failed'].includes(pattern!.status)); assert.ok(Number.isFinite(pattern!.confirmation_level)); assert.ok(Number.isFinite(pattern!.invalidation_level)) }

test('metadata lists exactly twenty classical patterns', () => assert.equal(classicalPatternMetadata.patterns.length, 20))
test('metadata contains all reversal patterns', () => { for (const name of ['head_and_shoulders', 'inverse_head_and_shoulders', 'double_top', 'double_bottom', 'triple_top', 'triple_bottom', 'rounding_top', 'rounding_bottom']) assert.ok(classicalPatternMetadata.patterns.includes(name as never)) })
test('metadata contains all continuation patterns', () => { for (const name of ['ascending_triangle', 'descending_triangle', 'symmetrical_triangle', 'bullish_flag', 'bearish_flag', 'bullish_pennant', 'bearish_pennant', 'rectangle', 'rising_wedge', 'falling_wedge', 'cup_and_handle', 'channel']) assert.ok(classicalPatternMetadata.patterns.includes(name as never)) })
test('insufficient candles are unavailable', () => { const result = analyzeClassicalPatterns(flat(29)); assert.equal(result.available, false); assert.equal(result.patterns.length, 0) })
test('flat data does not fabricate patterns', () => { const result = analyzeClassicalPatterns(flat(60)); assert.equal(result.patterns.length, 0) })
test('Head and Shoulders is detected', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'head_and_shoulders'), 'head_and_shoulders') })
test('Inverse Head and Shoulders is detected', () => { const values = extremaSeries([100, 100, 90, 80, 90, 100, 90, 70, 90, 100, 89, 79, 90, 100, ...Array(46).fill(95)]); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'inverse_head_and_shoulders'), 'inverse_head_and_shoulders') })
test('Double Top is detected with matched peaks', () => { const values = extremaSeries([...Array(8).fill(105), 120, 105, 100, 105, 119, 105, ...Array(48).fill(106)]); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'double_top'), 'double_top') })
test('Double Bottom is detected with matched troughs', () => { const values = extremaSeries([...Array(8).fill(105), 90, 105, 110, 105, 91, 105, ...Array(48).fill(106)]); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'double_bottom'), 'double_bottom') })
test('Triple Top is detected', () => { const values = extremaSeries([...Array(5).fill(105), 120, 105, 100, 105, 119, 105, 100, 105, 121, ...Array(45).fill(106)]); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'triple_top'), 'triple_top') })
test('Triple Bottom is detected', () => { const values = extremaSeries([...Array(5).fill(105), 90, 105, 110, 105, 91, 105, 110, 105, 89, ...Array(45).fill(106)]); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'triple_bottom'), 'triple_bottom') })
test('Rounding patterns require long history', () => { assert.equal(analyzeClassicalPatterns(flat(30)).patterns.some(p => p.name === 'rounding_bottom'), false); assert.equal(analyzeClassicalPatterns(flat(30)).patterns.some(p => p.name === 'rounding_top'), false) })
test('Ascending Triangle is detected', () => assertPattern(analyzeClassicalPatterns(triangle('ascending')).patterns.find(p => p.name === 'ascending_triangle'), 'ascending_triangle'))
test('Descending Triangle is detected', () => assertPattern(analyzeClassicalPatterns(triangle('descending')).patterns.find(p => p.name === 'descending_triangle'), 'descending_triangle'))
test('Symmetrical Triangle is detected', () => assertPattern(analyzeClassicalPatterns(triangle('symmetrical')).patterns.find(p => p.name === 'symmetrical_triangle'), 'symmetrical_triangle'))
test('Bullish Flag is detected after upward pole', () => assertPattern(analyzeClassicalPatterns(flag(true)).patterns.find(p => p.name === 'bullish_flag'), 'bullish_flag'))
test('Bearish Flag is detected after downward pole', () => assertPattern(analyzeClassicalPatterns(flag(false)).patterns.find(p => p.name === 'bearish_flag'), 'bearish_flag'))
test('Pennant names are part of the supported contract', () => { assert.ok(classicalPatternMetadata.patterns.includes('bullish_pennant')); assert.ok(classicalPatternMetadata.patterns.includes('bearish_pennant')) })
test('Rectangle requires repeated boundary contacts', () => { const values = flat(60); for (let i = 40; i < 60; i++) values[i] = c(i, i % 2 ? 119 : 101); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'rectangle'), 'rectangle') })
test('Rising and Falling Wedge names are supported', () => { assert.ok(classicalPatternMetadata.patterns.includes('rising_wedge')); assert.ok(classicalPatternMetadata.patterns.includes('falling_wedge')) })
test('Cup and Handle has a dedicated detector contract', () => { assert.ok(classicalPatternMetadata.patterns.includes('cup_and_handle')); assert.equal(analyzeClassicalPatterns(flat(40)).patterns.some(p => p.name === 'cup_and_handle'), false) })
test('Channel requires directional movement', () => { const values = flat(60); for (let i = 40; i < 60; i++) values[i] = c(i, 100 + (i - 39) * 1.2); assertPattern(analyzeClassicalPatterns(values).patterns.find(p => p.name === 'channel'), 'channel') })
test('H&S target uses measured move below neckline', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); const pattern = analyzeClassicalPatterns(values).patterns.find(p => p.name === 'head_and_shoulders'); assert.ok(pattern?.target); assert.ok(pattern!.target! < Number(pattern!.points.neckline)) })
test('Inverse H&S target uses measured move above neckline', () => { const values = extremaSeries([100, 100, 90, 80, 90, 100, 90, 70, 90, 100, 89, 79, 90, 100, ...Array(46).fill(95)]); const pattern = analyzeClassicalPatterns(values).patterns.find(p => p.name === 'inverse_head_and_shoulders'); assert.ok(pattern?.target); assert.ok(pattern!.target! > Number(pattern!.points.neckline)) })
test('pattern duration is positive', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); for (const pattern of analyzeClassicalPatterns(values).patterns) assert.ok(pattern.duration_days > 0) })
test('strength follows confidence', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); for (const pattern of analyzeClassicalPatterns(values).patterns) assert.ok(['weak', 'moderate', 'strong'].includes(pattern.strength)) })
test('volume warning is emitted without volume', () => { const result = analyzeClassicalPatterns(flat(60).map(value => ({ ...value, volume: undefined }))); assert.ok(result.data_quality.warnings.length > 0) })
test('duplicate pattern names are removed', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); const names = analyzeClassicalPatterns(values).patterns.map(p => p.name); assert.equal(new Set(names).size, names.length) })
test('every detected pattern has Arabic name and calculation', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); for (const pattern of analyzeClassicalPatterns(values).patterns) { assert.ok(pattern.nameAr.length > 0); assert.ok(pattern.target_calculation.length > 0) } })
test('all target values are finite when present', () => { const values = extremaSeries([100, 100, 110, 120, 110, 100, 110, 130, 110, 100, 110, 121, 110, 100, ...Array(46).fill(105)]); for (const pattern of analyzeClassicalPatterns(values).patterns) if (pattern.target != null) assert.ok(Number.isFinite(pattern.target)) })
test('failed/forming/confirmed are the only statuses', () => { const values = triangle('ascending'); for (const pattern of analyzeClassicalPatterns(values).patterns) assert.ok(['forming', 'confirmed', 'failed'].includes(pattern.status)) })
