import assert from 'node:assert/strict'
import test, { after, before } from 'node:test'
import { AnalysisOrchestrator, ANALYSIS_ENGINE_NAMES, safeEngine } from '../src/services/analysis/orchestrator.js'
import { CandlesService } from '../src/services/market/candles.service.js'
import { makeDataQuality } from '../src/services/market/data-quality.js'

function candles(count = 500, offset = 0) { return Array.from({ length: count }, (_, index) => { const value = 100 + offset + Math.sin(index / 7) * 6 + index * 0.04; return { date: new Date(Date.UTC(2024, 0, index + 1)).toISOString().slice(0, 10), open: value, high: value + 2, low: value - 2, close: value, volume: 1_000_000 + index * 1000 } }) }
const fixtureQuality = () => makeDataQuality({ status: 'delayed', provider: 'fixture-provider', timestamp: new Date().toISOString(), warnings: ['fixture'] })

const originalGetCandles = CandlesService.getCandles
before(() => {
	CandlesService.getCandles = (async (symbol: string, market: any) => ({ symbol, market, interval: '1d', candles: candles(500, symbol === 'ABUK' ? 20 : 0), source: 'market', fetched_at: new Date().toISOString(), count: 500, freshness: 'delayed', delayedByMinutes: 15, data_quality: fixtureQuality() })) as unknown as typeof CandlesService.getCandles
	AnalysisOrchestrator.clearCache()
})
after(() => { CandlesService.getCandles = originalGetCandles; AnalysisOrchestrator.clearCache() })

test('declares exactly fifteen integrated engines', () => assert.equal(ANALYSIS_ENGINE_NAMES.length, 15))
test('engine names are unique', () => assert.equal(new Set(ANALYSIS_ENGINE_NAMES).size, 15))
test('safeEngine returns data and quality metadata', async () => { const value = await safeEngine('ok', () => ({ available: true, data: { signal: 'BUY' }, source: 'unit' }), 100, 'fixture', new Date().toISOString()); assert.equal(value.available, true); assert.equal(value.source, 'unit'); assert.equal(value.data_quality.provider, 'market') })
test('safeEngine isolates a rejected engine', async () => { const value = await safeEngine('failed', async () => { throw new Error('expected_failure') }, 100, 'fixture', new Date().toISOString()); assert.equal(value.available, false); assert.match(value.error ?? '', /expected_failure/) })
test('safeEngine enforces an independent timeout', async () => { const value = await safeEngine('slow', () => new Promise(resolve => setTimeout(() => resolve({ value: 1 }), 50)), 5, 'fixture', new Date().toISOString()); assert.equal(value.available, false); assert.match(value.error ?? '', /timeout/) })
test('COMI returns a complete analysis object', async () => { AnalysisOrchestrator.clearCache(); const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.equal(value.symbol, 'COMI'); assert.equal(value.market, 'EGX'); assert.equal(value.candles.count, 500); assert.ok(value.fetched_at) })
test('COMI returns all fifteen engine keys', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); for (const name of ANALYSIS_ENGINE_NAMES) assert.ok(name in value) })
test('COMI integrity uses fifteen engines', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.equal(value.integrity.engines_total, 15); assert.equal(value.integrity.score, Math.round(value.integrity.engines_ok / 15 * 100)) })
test('COMI integrity is at least eighty with resilient local engines', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.ok(value.integrity.score >= 80, JSON.stringify(value.integrity)) })
test('first COMI request is not a cache hit', async () => { AnalysisOrchestrator.clearCache('COMI', 'EGX'); const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.equal(value.cache_hit, false); assert.equal(value.integrity.cache_hit, false) })
test('second COMI request is a cache hit', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.equal(value.cache_hit, true); assert.equal(value.integrity.cache_hit, true); assert.equal(value.execution_time_ms, 0) })
test('ABUK succeeds with an independent cache key', async () => { AnalysisOrchestrator.clearCache('ABUK', 'EGX'); const value = await AnalysisOrchestrator.analyze('ABUK', 'EGX'); assert.equal(value.symbol, 'ABUK'); assert.equal(value.cache_hit, false) })
test('COMI and ABUK outputs differ on different input series', async () => { const comi = await AnalysisOrchestrator.analyze('COMI', 'EGX'); const abuk = await AnalysisOrchestrator.analyze('ABUK', 'EGX'); assert.notDeepEqual(comi.indicators.data, abuk.indicators.data) })
test('every engine exposes latency and error fields', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); for (const name of ANALYSIS_ENGINE_NAMES) { const engine = value[name]; assert.ok(engine.latency_ms >= 0); assert.ok('error' in engine); assert.ok('data_quality' in engine) } })
test('every engine exposes a normalized data quality status', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); for (const name of ANALYSIS_ENGINE_NAMES) assert.ok(['live', 'same_day', 'historical', 'unavailable'].includes(value[name].data_quality.status)) })
test('engine source is preserved', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.ok(value.elliott.data_quality.provider) })
test('top signals are capped at five', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.ok(value.top_signals.length <= 5) })
test('top signals are sorted by descending confidence', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); for (let i = 1; i < value.top_signals.length; i++) assert.ok(value.top_signals[i - 1].confidence >= value.top_signals[i].confidence) })
test('top signals use the supported signal vocabulary', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); for (const signal of value.top_signals) assert.ok(['BUY', 'SELL', 'NEUTRAL'].includes(signal.signal)) })
test('backtesting is isolated from other engine failures', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.ok(value.backtesting.data !== undefined); assert.ok(value.indicators.available) })
test('confluence and recommendation are returned independently', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.ok('confluence' in value); assert.ok('recommendation' in value) })
test('debug payload can be derived without engine data bodies', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); const debug = Object.fromEntries(ANALYSIS_ENGINE_NAMES.map(name => [name, { available: value[name].available, latency_ms: value[name].latency_ms, error: value[name].error }])); assert.equal(Object.keys(debug).length, 15); assert.equal((debug.elliott as any).data, undefined) })
test('integrity warnings include source validation warnings', async () => { const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.ok(value.integrity.warnings.includes('fixture') || Array.isArray(value.integrity.warnings)) })
test('cache can be cleared for one symbol', async () => { AnalysisOrchestrator.clearCache('COMI', 'EGX'); const value = await AnalysisOrchestrator.analyze('COMI', 'EGX'); assert.equal(value.cache_hit, false) })
test('cache can be cleared globally', async () => { AnalysisOrchestrator.clearCache(); assert.equal(AnalysisOrchestrator.cacheSize(), 0) })
test('insufficient candles return fifteen unavailable engines', async () => { CandlesService.getCandles = (async () => ({ symbol: 'SHORT', market: 'EGX', interval: '1d', candles: candles(10), source: 'market', fetched_at: new Date().toISOString(), count: 10, freshness: 'delayed', delayedByMinutes: 15, data_quality: fixtureQuality() })) as unknown as typeof CandlesService.getCandles; AnalysisOrchestrator.clearCache('SHORT', 'EGX'); const value = await AnalysisOrchestrator.analyze('SHORT', 'EGX'); assert.equal(value.integrity.engines_ok, 0); assert.equal(value.integrity.engines_total, 15); assert.equal(value.elliott.available, false); CandlesService.getCandles = (async (symbol: string, market: any) => ({ symbol, market, interval: '1d', candles: candles(500, symbol === 'ABUK' ? 20 : 0), source: 'market', fetched_at: new Date().toISOString(), count: 500, freshness: 'delayed', delayedByMinutes: 15, data_quality: fixtureQuality() })) as unknown as typeof CandlesService.getCandles })
test('cache size reflects completed analyses', () => assert.ok(AnalysisOrchestrator.cacheSize() >= 1))
test('execution time is finite and below fifteen seconds', async () => { const value = await AnalysisOrchestrator.analyze('ABUK', 'EGX'); assert.equal(Number.isFinite(value.execution_time_ms), true); assert.ok(value.execution_time_ms < 15_000) })
